### ISSUE TITLE
ABI 115 & 116

### ISSUE THREAD

**Issue by threatcon** [electron/node-abi#155]
The registry does not show a 115 or 117 but (2) 116s. Is that correct?

**Comment by dsanders11** [comment]
115 belongs to Node.js v20, but you're correct, Electron v26 accidentally has the same ABI number (116) as Electron v25. Since there's already been quite a few v26 releases, and v26 is scheduled to go EOL in a couple months, I think we will leave the ABI number as-is, changing it this late might cause more problems than it is worth.

Thanks for the report. 👍
